# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build

on:
  push:
    branches: [ compilesinglefile ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20

    - name: Install dependencies
      run: npm ci && npm install webpack webpack-cli && npm install --save-dev @babel/core @babel/preset-env babel-loader

    - run: npm run lint
    - run: npm run test

    - name: Run Webpack
      run: npx webpack

    - name: Tar out folder
      working-directory: ./dist
      run: tar -czvf dist.tar.gz ./*

    - name: Get current date
      id: date
      run: echo "date=$(date +'%Y_%m_%d_%H_%M_%S')" >> $GITHUB_OUTPUT

    - name: Create release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{  github.ref_name }}
      run: |
        gitsha=$(git rev-parse --short "$GITHUB_SHA"); gh release create "$tag_$gitsha" dist/dist.tar.gz \
            --repo="$GITHUB_REPOSITORY" \
            --title="${GITHUB_REPOSITORY#*/} ${tag#v}" \
            --notes "Generated on ${{ steps.date.outputs.date }}"
